### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by h2o64**
There's no gerrit so I do a pull request

### CODE REVIEW

**Comment by h2o64** [comment]
CHANGES ADDED TO THE PULL REQUEST :
https://github.com/h2o64/device_yu_lettuce/commit/f20061cdd7bafcd10402324e25e49f6038b34a85
https://github.com/h2o64/device_yu_lettuce/commit/fb718843246c454490e6ed9b1b7c0f40c6c9c267
https://github.com/h2o64/device_yu_lettuce/commit/f10ee557c86c090a25b193d059357ea8501899c6

**Comment by brijeshmmx** [comment]
git clone http://codereview.yuplaygod.com/YUTeleventures/device_yu_lettuce  added, great if you can push changes directly to gerrit. Thanks

**Comment by h2o64** [comment]
I'll do

**Comment by AudioGod** [comment]
@h2o64  so lets close this pull request.

**Pull request closed without merging**
